- name: 'Check passphrase presence'
  assert:
    that:
      - passphrase is defined
    fail_msg: "{{passphrase}} needs to be set for the role to work "
    success_msg: "Required variable {{passphrase}} is defined"

- name: "Create General Certificates directory for Docker"
  file:
    path: "{{certdir}}"
    owner: ansible
    group: ansible
    state: directory
  become: yes
  
- name: Generate an OpenSSL public key
  community.crypto.openssl_privatekey:
    cipher: aes256
    size: 2048
    passphrase: "{{passphrase}}"
    path: "{{certdir}}/ca-key.pem"
    mode: 0644
    owner: ansible
    group: ansible
 
- name: Generate an OpenSSL server key
  community.crypto.openssl_privatekey:
    size: 4096
    path: "{{certdir}}/server-key.pem"
    mode: 0644  
    owner: ansible
    group: ansible

- name: Generate an OpenSSL Certificate Signing Request
  community.crypto.openssl_csr:
    privatekey_path: "{{certdir}}/server-key.pem"
    digest: sha256
    path: "{{certdir}}/server.csr"
    mode: 0644
    owner: ansible
    group: ansible

- name: Re-Generate an OpenSSL Certificate
  block:
    - name: Generate csr for certificate
      community.crypto.openssl_csr:
        path: "{{certdir}}/ca-csr.csr"
        privatekey_path: "{{certdir}}/ca-key.pem"
        privatekey_passphrase: "{{passphrase}}"
        country_name: "{{country_name}}"
        organization_name: "{{organization_name}}"
        email_address: "{{email_address}}"
        mode: 0644
        owner: ansible
        group: ansible

    - name: Generate certificate
      openssl_certificate:
        provider: selfsigned
        path: "{{certdir}}/ca.pem"
        privatekey_path: "{{certdir}}/ca-key.pem"
        privatekey_passphrase: "{{passphrase}}"
        csr_path: "{{certdir}}/ca-csr.csr"
        mode: 0644
        owner: ansible
        group: ansible

- name: Generate a Self Signed OpenSSL certificate
  openssl_certificate:
    path: "{{certdir}}/server-cert.pem"
    ownca_privatekey_path: "{{certdir}}/ca-key.pem"
    csr_path: "{{certdir}}/server.csr"
    ownca_path: "{{certdir}}/ca.pem"
    provider: ownca
    ownca_privatekey_passphrase: "{{passphrase}}"
    mode: 0644
    owner: ansible
    group: ansible

- name: Generate an OpenSSL client key
  community.crypto.openssl_privatekey:
    size: 4096
    path: "{{certdir}}/key.pem"
    mode: 0644
    owner: ansible
    group: ansible

- name: Generate an OpenSSL Certificate Signing Request
  community.crypto.openssl_csr:
    privatekey_path: "{{certdir}}/key.pem"
    path: "{{certdir}}/client.csr"
    mode: 0644
    owner: ansible
    group: ansible

- name: Generate a Self Signed OpenSSL certificate
  openssl_certificate:
    path: "{{certdir}}/cert.pem"
    ownca_privatekey_path: "{{certdir}}/ca-key.pem"
    csr_path: "{{certdir}}/client.csr"
    ownca_path: "{{certdir}}/ca.pem"
    provider: ownca
    ownca_privatekey_passphrase: "{{passphrase}}"
    mode: 0644
    owner: ansible
    group: ansible