- name: Install requirements
  vars:
    - ansible_python_interpreter: /usr/bin/python2
  tasks:
    - name: Install {{item}}
      package:
        name: "{{item}}"
        state: present
      with_items:
        - python3
        - pyOpenSSL
        - libselinux-python3
    - name: Install docker
      block:
      - name: Install yum-utils
        package:
          name: yum-utils
          state: present
      - name: Add Latest Docker repository
        command: "sudo yum-config-manager \
          --add-repo \
          https://download.docker.com/linux/centos/docker-ce.repo"
      - name: Install Docker engine
        block:
          - name: Install docker-ce
            package:
              name: docker-ce
              state: present
          - name: Install docker-ce-cli
            package:
              name: docker-ce-cli
              state: present
          - name: Install containerd.io
            package:
              name: containerd.io
              state: present
