- name: "Create Certificates directory for Docker"
  file:
    path: "{{ certificates_dir }}"
    state: directory
  become: yes

- name: "Push Certificate to Server"
  become: yes
  copy:
    src: "{{ server_certificate }}"
    dest: "{{ certificates_dir }}/server-certificate.pem"

- name: "Push RootCA to Server (For client verification)"
  become: yes
  copy:
    src: "{{ rootca_certificate }}"
    dest: "{{ certificates_dir }}/rootca-certificate.pem"