- name: "Create Certificates directory for Docker"
  file:
    path: "{{ certificates_dir }}"
    state: directory
  become: yes

- name: "Create Certificates directory for client"
  connection: local
  delegate_to: localhost
  file:
    path: "{{ client_certificates_dir }}"
    state: directory
  become: yes


- name: "Move Server Key"
  become: yes
  copy:
    remote_src: yes
    src: "{{ server_privatekey }}"
    dest: "{{ certificates_dir }}/server-privatekey.pem"

- name: "Push Certificate to Server"
  become: yes
  copy:
    src: "{{ server_certificate }}"
    dest: "{{ certificates_dir }}/server-certificate.pem"

- name: "Push RootCA to Server (For client verification)"
  become: yes
  copy:
    src: "{{ rootca_certificate }}"
    dest: "{{ certificates_dir }}/rootca-certificate.pem"

- name: "Move client certificates to docker directory"
  connection: local
  delegate_to: localhost
  copy:
    src: "{{item}}"
    dest: "{{ client_certificates_dir }}"
  with_items:
    - "{{certdir}}/key.pem"
    - "{{certdir}}/ca.pem"
    - "{{certdir}}/cert.pem"