- name: Install python3
  yum:
    name: python3
    state: present

- name: Install python3
  yum:
    name: pyOpenSSL
    state: present

- name: Install Libslinux
  yum:
    name: libselinux-python3
    state: present