- name: Install python3
  yum:
    name: python3
    state: present

- name: Install pyOpenSSL
  yum:
    name: pyOpenSSL
    state: present

- name: Install Libslinux
  yum:
    name: libselinux-python3
    state: present

- name: Install docker
  block:
    - name: Install yum-utils
      yum:
        name: yum-utils
        state: present
    - name: Add Latest Docker repository
      command: "sudo yum-config-manager \
        --add-repo \
        https://download.docker.com/linux/centos/docker-ce.repo"
    - name: Install Docker engine
      block:
        - name: Install docker-ce
          yum:
            name: docker-ce
            state: present
        - name: Install docker-ce-cli
          yum:
            name: docker-ce-cli
            state: present
        - name: Install containerd.io
          yum:
            name: containerd.io
            state: present
