- name: "Install requirements"
  include_tasks: _install_requirements.yml

- name: "Install Docker"
  include_tasks: _install_docker.yml

- name: "Create certificates"
  include_tasks: _create_certificates.yml

- name: "Install Certificates"
  include_tasks: _install_certificates.yml

- name: "Setup Docker daemon Service"
  include_tasks: _setup_docker_service.yml
